package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Verify title tonichealthcare")
    void generatedTest() {
        step("open https://tonicforhealth.com/", () -> {
            step("// todo: just add selenium action");
        });

        step("check label \"Tonic Joined R1 RCM to Reimagine the Patient Experience\"", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://tonicforhealth.com/'", () ->
            open("https://tonicforhealth.com/"));

        step("Page title should have text 'Tonic Health: World’s Best Patient Data Collection and Payments Platform.'", () -> {
            String expectedTitle = "Tonic Health: World’s Best Patient Data Collection and Payments Platform.";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://tonicforhealth.com/'", () ->
            open("https://tonicforhealth.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}